### ISSUE TITLE
TOC links in docs don't work

### ISSUE THREAD

**Issue by gaearon** [reduxjs/redux#3090] opened 2018-08-08 22:50 UTC
When I click on any table of contents link on e.g. https://redux.js.org/faq/general, nothing happens. In general it seems like anchors are broken?

**Comment by markerikson** [comment] 2018-08-09 00:32
Are you talking about the hand-written ones at the top of the FAQ pages, or the auto-generated ones on the side?

The hand-written ones have been busted since the Gitbook upgrade a few months ago.  @SamyPesse said they were going update their parser to account for those, but nothing's happened.  

Technically this is a dupe of #3061 .

The auto-generated TOC is actually kind of nice, but my main reason for doing the hand-written ones in the first place is that it's a lot nicer to paste in https://redux.js.org/faq/actions#actions-side-effects instead of https://redux.js.org/faq/actions#how-can-i-represent-side-effects-such-as-ajax-calls-why-do-we-need-things-like-action-creators-thunks-and-middleware-to-do-async-behavior , so it'd be nice if we had those working again.  (Or, a way to force the auto-generated TOC to use the shorter versions.)

**Comment by Nicholas-Eng** [comment] 2018-08-10 15:36
Hi, I think this issue has to do with the "id" and lack of "name" attributes used on the <a/>. See this [post ](https://stackoverflow.com/questions/5319754/cross-reference-named-anchor-in-markdown/7335259#7335259) for more information.

Is it alright if I take this one as my first issue?

**Comment by markerikson** [comment] 2018-08-10 16:27
@Nicholas-Eng : if you can figure out a way to make it work, great!  Unfortunately, we don't have any kind of PR changes preview set up for the docs, and my understanding is that Gitbook does more than "just" a standard Markdown transform, so I'm not sure there's a way to verify that changes actually fix the issue other than merging them in.

Based on prior discussions, it sounds as if this is a weakness in Gitbook's transformation logic, and they haven't gotten around to fixing it.

**Comment by Nicholas-Eng** [comment] 2018-08-10 17:47
I agree. This looks more like an issue on Gitbook's end. I do see that the ids are missing from the anchor tags in the auto generated HTML, so that's why they aren't navigating to the sections.

**Comment by gaearon** [comment] 2018-08-10 18:25
Shall we remove all TOCs then? It's super confusing.

**Comment by gaearon** [comment] 2018-08-10 18:27
Also why does it attempt to load Mixpanel? Are we logging analytics for Redux doc readers? Why?

**Comment by Nicholas-Eng** [comment] 2018-08-10 18:40
I would recommend leaving the right pane ToC and either commenting out or removing the hand-written ToC for now. Maybe once the issue is resolved with Gitbook then bring back the hand-written ToC.

**Comment by timdorr** [comment] 2018-08-10 19:11
> Also why does it attempt to load Mixpanel? Are we logging analytics for Redux doc readers? Why?

That's just part of the platform. We have access to see those numbers. It's particularly helpful to know what docs are most viewed and therefore should receive the most scrutiny when writing them.

**Comment by SamyPesse** [comment] 2018-08-10 20:42
@markerikson Sorry for the late reply, I was quite off this summer.

> my understanding is that Gitbook does more than "just" a standard Markdown transform

Yes, we are parsing the markdown to a JSON semantic format ([here is the output of one of your page](https://blobscdn.gitbook.com/v0/b/gitbook-28427.appspot.com/o/documents%2F-L5K1I1WsuQMZ8ecEuWg%2F-LH3KYV1I_bKCs-ve0VW%2Fmaster%2F-L5K1IE59DRP1u8cCBOi%2Fdocument.json?generation=1531228627332155&alt=media)). Raw HTML (which are not semantic) are stripped or transformed.

The main issue with custom IDs for headings is that there is no official syntax in Markdown. For example, in your case you are using an HTML element to create an anchor right before the heading (`<a id="custom-id"></a>`).

Since a few weeks ago, using the WYSIWYG editor, it's possible to edit the IDs. For markdown serialization, we've started supporting a syntax from [Kramdown](https://kramdown.gettalong.org/syntax.html#specifying-a-header-id):

```
# Hello {#custom-id}
```

**But this syntax is not supported by GitHub**. That's the reason I didn't come back to you with this solution (as it'll make the markdown less readable on GitHub).

But we are still considering supporting the HTML anchor solution in our [Markdown parser](https://github.com/GitbookIO/markup-it).

The other solution will be using the kramdown syntax, What's your take on it?

---

> When I click on any table of contents link on e.g. redux.js.org/faq/general, nothing happens. In general it seems like anchors are broken?

@gaearon It looks a bug, are you talking about the right or left table of content ?

---

> Also why does it attempt to load Mixpanel? Are we logging analytics for Redux doc readers? Why?

@gaearon The new GitBook is a full WYSIWYG application. Most teams using GitBook are editing content on our platform. In the Redux case, you are using GitBook only as an output generator.

To better understand our users we have to measure activity (mostly when the user edits the content). In the case of readers, the only tracked event is the vote on the page quality, this information is shared with the content owner in the ["Insight" dashboard](https://user-images.githubusercontent.com/845425/43980477-9038a03a-9cee-11e8-9997-ea9698010a72.png).

Let me know if you think it could be an issue for your readers.

**Comment by markerikson** [comment] 2018-08-10 21:07
@SamyPesse : if you could support the HTML anchor approach, that would probably be simplest because we already have those in place.

On the other hand, we do have two separate TOCs - the hand-written ones inline at the top of the pages, and the auto-generated ones on the right.  Is there any way we can get the auto-generated TOC to reflect the shorter anchor names?  As I said earlier - my biggest reason for doing this is simply to have shorter, easier-to-read links to paste when directing people to a given FAQ entry.

**Closed** 2018-12-13 15:36 UTC
Labels: docs, help wanted
