### ISSUE TITLE
[Docs] Incorrect claim regarding /fakeApi/notifications response body

### ISSUE THREAD

**Issue by nanyaDev** [reduxjs/redux#4592] opened 2023-08-23 16:44 UTC
In  _Redux Essentials, Part 6: Performance and Normalizing Data_ it says:

> Our fake API is already sending back the notification entries with `isNew` and `read` fields, so we can use those in our code.

The fake API doesn't doesn't actually send back notification entries with those fields. The response body for `/fakeApi/notifications` has the following shape (taken from my network tab): 

```json
[
    {
        "id": "dRlbcYxqEfaHY7--PSjDP",
        "date": "2023-08-23T16:20:17.229Z",
        "message": "is glad we're friends",
        "user": "KEsh5ntGEPkFQuJ2faaD5"
    },
    {
        "id": "V35OKeoD09Bgo3KCAWezR",
        "date": "2023-08-23T16:19:22.420Z",
        "message": "sent you a gift",
        "user": "KEsh5ntGEPkFQuJ2faaD5"
    },
    {
        "id": "uPCHUku1wC4ZtraWz4tgn",
        "date": "2023-08-23T16:23:40.075Z",
        "message": "poked you",
        "user": "KEsh5ntGEPkFQuJ2faaD5"
    }
]
```

I've checked the network request, the source code in `server.js` and even searched the entire repo and there is no mention of those fields.

**Comment by timdorr** [comment] 2023-08-23 22:12
Duplicate of reduxjs/redux-essentials-example-app#20

**Closed by timdorr** 2023-08-23 22:12 UTC
