### ISSUE TITLE
Support including in rollup projects without extra plugins/hacks

### ISSUE THREAD

**Issue by rjsteinert** [reduxjs/redux#3073] opened 2018-07-25 13:01 UTC
**What is the current behavior?**

Doing `import { createStore } from 'redux'` in a rollup project results in console error in browser`redux.js:615 Uncaught ReferenceError: process is not defined`. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar.**

https://polymer-with-redux.glitch.me/

**What is the expected behavior?**

To not crash and not have to do any of the work arounds described [in this rollup issue](https://github.com/rollup/rollup/issues/487) because sometimes we're in a situation where we can't / don't want to mess with rollup as is the case in a Polymer CLI project ([related issue](https://github.com/Polymer/tools/issues/406))

**Which versions of Redux, and which browser and OS are affected by this issue? Did this work in previous versions of Redux?**
Redux 4.0.0. I'm just testing in latest Chrome but I'm sure we'll see this everywhere. I'm not sure if it worked in previous versions of Redux.

**Comment by timdorr** [comment] 2018-07-25 15:33
Dupe of #2907

**Closed by timdorr** 2018-07-25 15:33 UTC
