### ISSUE TITLE
dynamic reducers can not work with combineReducers

### ISSUE THREAD

**Issue by H3lloTom** [reduxjs/redux#3643] opened 2019-11-30 12:27 UTC
## Do you want to request a _feature_ or report a _bug_?
bug

## Bug Reports
i have an app, whats reducer is dynamic. the reducer is combined by combineReducers,but combineReducers seems have a cache Strategy, if new reducer map have the same result in old state, after traversal, it will return old state.even if the new reducer map has less reducer key than old reducer map, in this case i want to get exact next state after i invoke replaceReducer.🙂

### What is the current behavior?
combineReducers return old state in the case next reducer map has less key than previous reducer map.

### Steps to Reproduce
👉 https://codesandbox.io/s/interesting-chandrasekhar-h56kh?fontsize=14&hidenavigation=1&theme=dark 👈
### What is the expected behavior?
combineReducers return next state in the case: next reducer map has less key than previous reducer map.

### Which versions of Redux, and which browser and OS are affected by this issue? Did this work in previous versions of Redux?
redux 4.0.4

### What docs changes are needed to explain this?
if combineReducers could not work with replaceReducer in this case, i wish could got a office notice😁

**Comment by markerikson** [comment] 2019-11-30 16:03
`combineReducers` has had a special check for the `REPLACE` action for over two years, so it's not like this is a recent change:

https://github.com/reduxjs/redux/pull/2673

However, I do agree this is rather unexpected from the user's point of view.

@timdorr , thoughts?

**Comment by H3lloTom** [comment] 2019-11-30 17:10
🎉🎉🎉thanks for replying so quickly ,but i could only find a special check for `REPLACE` action in `warningMessage`,

it seems still have my situation,while i do `replaceReducer` with a less reducer map 
(the old reducer`combineReducers({a:()=>'a',b:()=>'b'})` => new reducer`combineReducers({a:()=>'a'})`),

the `combineReducers` returned `combination` func deal `REPLACE` action, still return old state `{a:'a',b:'b'}`,meanwhile,b is not in my new reducer🤔

**Comment by timdorr** [comment] 2019-11-30 21:28
Duplicate of #3488 and was fixed in #3490, but we haven't released it yet.

**Closed by timdorr** 2019-11-30 21:28 UTC
