### ISSUE TITLE
https://github.com/reduxjs/redux/tree/master/examples/todos-flow Is outdated

### ISSUE THREAD

**Issue by TomasBarry** [reduxjs/redux#3991] opened 2021-01-08 10:14 UTC
## What docs page needs to be fixed?

https://github.com/reduxjs/redux/tree/master/examples/todos-flow

## What is the problem?

`redux` no longer exports the `Store` and `Dispatch` (or any) Flow types. Additionally, the version of `flow-bin` in this example is very far behind the latest version of `flow-bin` (`0.142.0`).

Second to this, actually running `npm flow` on a fresh build of this project results in 63 Flow errors.

## What should be changed to fix the problem?

This example should be updated or removed if `redux` no longer intends to provide examples of using `redux` with Flow.

**Comment by timdorr** [comment] 2021-01-08 15:26
Yeah, I don't really know Flow and that was only added by contribution. We should probably remove it, given Flow's waning popularity.

**Comment by markerikson** [comment] 2021-01-08 17:23
Yeah, this issue is really a dupe of #3917 .

**Closed by markerikson** 2021-01-08 17:23 UTC
