### ISSUE TITLE
Argument of type 'AsyncThunkAction<{ id: number; }, void, AsyncThunkConfig>' is not assignable to parameter of type 'UnknownAction'.

### ISSUE THREAD

**Issue by seafronthu** [reduxjs/redux#4694] opened 2024-04-03 07:32 UTC
![image](https://github.com/reduxjs/redux/assets/50374650/6ae57e97-9053-4208-b5e1-ad803466dd63)
I made a [demo](https://stackblitz.com/edit/stackblitz-starters-9mcxze?file=src%2FApp.tsx,src%2Findex.tsx), it does not work after defining the typed hooks, And the vscode has the same issue, So It's not a bug with stackblitz's typescript server.

`"react-redux": "^9.1.0"`
`"@reduxjs/toolkit": "^2.2.2"`
`"@types/react": "^18.2.47"`
`"@types/react-dom": "^18.2.18"`
`"typescript": "^5.4.3"`
I don't know what caused it, it's too uncomfortable.

**Comment by EskiMojo14** [comment] 2024-04-03 08:14
duplicate of https://github.com/reduxjs/redux-toolkit/issues/4299, please don't open the same issue in multiple repos

**Closed by EskiMojo14** 2024-04-03 08:14 UTC
