### ISSUE TITLE
TypeScript Redux CodeSandbox 404

### ISSUE THREAD

**Issue by lgandecki** [reduxjs/redux#3996] opened 2021-01-18 10:47 UTC
## What docs page needs to be fixed?

- **Recipes**:
- **Usage With TypeScript**:

## What is the problem?

the "The full source code is available on codesandbox here. " points to 404

## What should be changed to fix the problem?
Point to an existing code sandbox :-)
I found something similar here - https://codesandbox.io/s/redux-typescript-example-forked-medu6 but it's a fork and I'm not sure what are the changes between it and the original code

**Comment by wtlin1228** [comment] 2021-02-24 06:47
The link is still broken.

**Comment by markerikson** [comment] 2021-02-24 15:01
Yeah, that's why the issue is still open :)

We need to rework the TS usage page to be more similar to https://redux-toolkit.js.org/tutorials/typescript .

**Comment by markerikson** [comment] 2021-03-21 16:56
Fixed by #4042 .

**Closed by markerikson** 2021-03-21 16:56 UTC
