### ISSUE TITLE
OtherActions<T> type and potentially update the Reducer type

### ISSUE THREAD

**Issue by ricokahler** [reduxjs/redux#4036] opened 2021-03-15 08:12 UTC
### What is the new or updated feature that you are suggesting?

`OtherActions<T>` type. (see https://github.com/reduxjs/redux/issues/4025#issuecomment-799198392 for context)

Given the problem @phryneas states in [his article](https://phryneas.de/redux-typescript-no-discriminating-union), unions are definitely prone to errors.

I think it could be valuable to ship a type helper `OtherActions<T>` that has the purpose of creating a complement set of actions for a given reducer.

The implementation of `OtherActions` would look like this:

```ts
type OtherActions<T extends AnyAction> = { type: T extends T['type'] ? T : { type: unknown } }
```

And its usage would look like this:

```ts
type Actions = SendMessageAction | DeleteMessageAction;

export function chatReducer(
  state = initialState,
  action: Actions | OtherActions<Actions>
): ChatState {

  switch (action.type) {
    case SEND_MESSAGE:
      return {
        messages: [...state.messages, action.messages]
      }
    case DELETE_MESSAGE:
      return {
        messages: state.messages // etc etc
      }
    // NOTE: notice how it errors if this is commented out
    // default:
    //   return state
  }
}
```

[TS Playground Link](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAlmOU4EMA2BlKKoFMYC8MA3jALa4QQoDmlAXDANoC6MAvgFCe4AeADiABOsUJFgYAogDkAIgH0AspIwYAggHFJhGAHIpcpSvVbdPAcNHhoMWZIAykgCqSjqzdqK67jl25OSZpwIeEIAZijA+ADCABY4WDj4pFzBYKERUTAYuGAAJoqU1HRqwMjgJDBQAJ78uIw1dSBh2TIKyu5aADTkRbQMMNBCCDSsANwcaRmR+LK4aLh4hVT9peVglY31VbW4zbYOzq4dAZOcWzBrcNY6OfnLxbhXFQA+tvOLuA+rZddgY+ddpcwNVnhsiKQtowUCDJhcAPJQWK4IRgiAAHicMD4eHyEGBoN+4AAfDpIbtGFicbk8vinExdFtdGwAPwwLGMcl1RgAVzAAGswCAAO4bdhnPiCEQwMJ8okbYDxKAAJVweR5USEAApODBBtg8DoEEhUJgDbgurqYJF1ow0TA3ojkaj5Ri0cTOABKRhxBLmkjcPUQYVIRUwLU2v4AOi2noDer1wBQEHwBnaxg89CtCZgQkWPKEG2I2ZzvRWdAgjCYUZr0CSUYo5coPUj4AbfQrLBLeq4OaTKYOvmOGa0WdLufzhfj47Lj0r+vrjbnMAA9CvsVBgBvgN3Jjm8rgIjy0FAx6W81ACxs63grVx2EA)

Additionally, I think it could be beneficial to use OtherActions in the definition of `Reducer<T>`

```ts
export type Reducer<S = any, A extends Action = AnyAction> = (
  state: S | undefined,
  action: A | OtherActions<A>
) => S
```

### Why should this feature be included?

This change here would make it so the action param includes the complement of any union given to it. This would force typescript users to return a default case.

![image](https://user-images.githubusercontent.com/10551026/111122483-7e68cd80-8544-11eb-8e75-7f6bcd8eee4f.png)

[TS Playground Link](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAlmOU4EMA2BlKKoFMYC8MA3jALa4QQoDmlAXDANoC6MAvgFCe4AeADiABOsUJFgYAogDkAIgH0AspIwYAggHFJhGAHIpcpSvVbdPAcNHhoMWZIAykgCqSjqzdqK67jl25OSZpwIeEIAZijA+ADCABY4WDj4pBRUtAww0EIINKwc3CG44ZH4GLhgACaKlNR0asDI4CQwUACe-LiMbR0gYTAGCsruWgA05DXpEIxZOawA3PmFxVG2uGi4eNVpdQ1wTaTdnS3tuL22Ds6uQwH5nIcw9Y2QOmWVW7W4j3tgMAA+q+tNhMdk85ncTg8wK0vk0iAcTowUFD8vcAPJQWJFGGQAA8ThgfDwlQgkOhu3AAD4dPCOox8YTyhUSU4mLpDro2AB+GD4xg0o4AVzAAGswCAAO4-di3e4AJVwFQFUSEOIwYzUBN4RKZpOxVKIAApODBMtg8IwMH8YEKKrgwggFSNjTBIk9GBr-ujMUJsRAcWoKZwAJSEKkYbhiGzAeJQeWK5WMONKoo4uIJM24dXkyD6mBGk3QJI6BBIVCYDNOk2u77B0MkbgF8VIaN56vgAB0hxDxGdJuAKAgpRkg2MHnovZNMCEGwFQh+Pcni-G2wyTHb68LeHbqQ+EDG6-bbbA2+BlBYE5NXEX-cH518V1HWnHS6nM7n9ZfJp3k2mGZPK5JAB6QCCSgYBQOAC98kXYCYGkVEXEYMVkBWWIJXgWAiiEYQSTgPoMTgXCSVAMgKDAPAKhgEABSgCdbQiAU0CgZ8l2nKBZx+TdcGdLguHMQQRBgeiUEY0QYyTZU5iAA)

### What docs changes are needed to explain this?

This would be included in #4025

**Comment by ricokahler** [comment] 2021-03-15 08:13
Related: #3580

**Comment by timdorr** [comment] 2021-03-15 16:50
I don't think this is actually going to solve any problems. Instead of having them remember to add a default case to their reducer, they now have to remember to use this extra type. That still puts the onus on the user and just shifts where they have to remember these things. So, it's a net zero gain.

Nonetheless, we already have an open issue for this. 

Duplicate of #3580

**Closed by timdorr** 2021-03-15 16:50 UTC
