### ISSUE TITLE
Text Not Visible in DARK MODE

### ISSUE THREAD

**Issue by AnirudhPanda** [reduxjs/redux#4142] opened 2021-07-30 18:50 UTC
## What docs page needs to be fixed?

- [This Page](https://redux.js.org/tutorials/essentials/part-1-overview-concepts)

## What is the problem?
![Capture](https://user-images.githubusercontent.com/66218496/127698225-4d1e6e8e-7ece-45bb-9619-8efa3fd5b44d.PNG)
![3](https://user-images.githubusercontent.com/66218496/127698238-6fad4890-af3e-46c5-b477-de6928349f3f.PNG)

## What should be changed to fix the problem?
On Light Mode the color of the `li` tags are black and on switching to the dark mode it turns white. Either we have to keep that on black even after switching to dark on just update the whole `admonition admonition-info` div's to dark

**Comment by timdorr** [comment] 2021-07-30 20:04
A duplicate of reduxjs/redux#4142.

If someone wants to submit a PR for either repo, we can make sure it gets replicated to the other.

**Closed by timdorr** 2021-07-30 20:04 UTC
