### ISSUE TITLE
Not using update redux state

### ISSUE THREAD

**Issue by Jacky9425** [reduxjs/redux#3659] opened 2019-12-18 10:17 UTC
## Do you want to request a _feature_ or report a _bug_?

i performed a background task using `react-native-background-fetch`, the task was to simply alter the existing redux state and on the next background task fires, if the state is altered, it should not execute the similar function again. However on the second fire, the previous state is still in non-altered state, when redux-logger shows that the state in reducer had already changed. (eg: `props.status` (component) is false, on first fire, `state.status `(reducer) is changed to true, hence on second fire, it should detect that `state.status` is already changed and will not dispatch the action again. But on second fire `props.status` remains **false**, but redux logger shows `state.status` is already **true**)

remarks: this only happens on headless (app quits by back press). Bringing app to background works as expected.

### Prior Issues

Are there any existing issues or PRs that relate to this problem? If so, link them here.

### What is the current behavior?
reducer state is changed but props remains previous value. 

### Steps to Reproduce
1. declare a background task to alter state, headless task registered (see `react-native-background-fetch` doc `registerHeadlessTask`)
2. app is close, and await background task fire
3. background task fire to change state

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://codesandbox.io or similar.

### What is the expected behavior?
on the next fire, the same action should not be dispatch again based on the changed state

### Environment Details

redux version: 3.7.2
react-native: 0.59.8
Android OS: android 8

### What docs changes are needed to explain this?
does headless task does not update the changed state into props?

**Comment by timdorr** [comment] 2019-12-18 16:39
This is either a duplicate of reduxjs/react-redux#1298 or something specific to how `react-native-background-fetch` works.

**Closed by timdorr** 2019-12-18 16:39 UTC

**Comment by Jacky9425** [comment] 2019-12-19 00:45
does not seem similar with the issue attached.
For my case i am not using PureComponent.
also i am not having re-rendering problems, just that the props is not updated with the new state and remains the previous state.

**Comment by Liestambeur** [comment] 2020-07-06 15:03
@Jacky9425 did you solve this issue? I'm having the same problem...
