### ISSUE TITLE
Codesandbox link broken in Typescript Docs

### ISSUE THREAD

**Issue by DedicatedManagers** [reduxjs/redux#4009] opened 2021-02-02 05:14 UTC
## What docs page needs to be fixed?
https://redux.js.org/recipes/usage-with-typescript#a-practical-example

## What is the problem?
Clicking on the link opens codesandbox with an error "Something went wrong. Request failed with status code 404"

## What should be changed to fix the problem?
Fix Link?

**Comment by timdorr** [comment] 2021-02-02 14:39
Duplicate of #3996

**Closed by timdorr** 2021-02-02 14:39 UTC
